package edu.northeastern.cs5500;
import java.util.List;

/**
 * interface to parse the data from the HTML report
 * @author abhiruchi
 *
 */
public interface IHTMLParser {
	
	/**
	 * method to parse the HTML report generated by the library.
	 * @return the important data from the report as a String.
	 */

	public List<PlagiarismResult> getSimilarityScore(String outputDir);
}
