package edu.northeastern.cs5500;

/**
 * interface to parse the data from the HTML report
 * @author abhiruchi
 *
 */
public interface IHTMLParser {
	
	/**
	 * method to parse the HTML report generated by the library.
	 * @return the important data from the report as a String.
	 */
	public String parse();
}
